# riscv-toolchain.cmake


set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)


# Override with -DTOOLCHAIN_PREFIX=... or the ARM_TOOLCHAIN_BIN env var
if(NOT TOOLCHAIN_PREFIX)
    if(DEFINED ENV{ARM_TOOLCHAIN_BIN})
        set(TOOLCHAIN_PREFIX $ENV{ARM_TOOLCHAIN_BIN})
    else()
        set(TOOLCHAIN_PREFIX $ENV{HOME}/toolchains/gcc-arm-none-eabi-8-2018-q4-major/bin)
    endif()
endif()

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}/arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}/arm-none-eabi-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}/arm-none-eabi-gcc)
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}/arm-none-eabi-objcopy)
set(CMAKE_SIZE ${TOOLCHAIN_PREFIX}/arm-none-eabi-size)


set(CMAKE_C_FLAGS "" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS "" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)