webtalk_init -webtalk_dir C:\\Users\\nmil\\1301_w_l\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-01-20 16:59:27" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pocdhclta2ql2bakgf2q3c8iu3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_27" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.191 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1768915216386" -context "sdk\\\\bsp/1768915216386"
webtalk_add_data -client sdk -key hwid -value "1768892694801" -context "sdk\\\\bsp/1768915216386"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1768915216386"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1768915216386"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1768915216386"
webtalk_add_data -client sdk -key uid -value "1768915217290" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key hwid -value "1768892694801" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key bspid -value "1768915216386" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key projSize -value "296.6796875" -context "sdk\\\\application/1768915217290"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key DebugCount -value "59" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1768917567567"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1768917567567"
webtalk_transmit -clientid 1642832754 -regid "" -xml C:\\Users\\nmil\\1301_w_l\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\nmil\\1301_w_l\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\nmil\\1301_w_l\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
